# Menentukan Image OS berbasis Ubuntu 24.04
image: Ubuntu2404

# Batasi trigger hanya saat push ke branch main
branches:
  only:
    - main

# Menonaktifkan pembacaan file solusi Visual Studio otomatis
build: off

# Caching folder modul Go & kompilasi build (Path pengguna 'appveyor')
cache:
  - ~/.cache/go-build            # Cache hasil kompilasi Go
  - ~/go/pkg/mod                 # Cache modul/dependensi Go
  - /var/cache/apt/archives      # Cache paket apt (opsional, menjaga agar apt install cepat)

# Langkah setup environment, instalasi tools dasar, kompilasi, dan kompresi
build_script:
  - go version
  # Install UPX dan LFTP sekaligus dalam 1 kali apt update (jika belum ada di sistem)
  - if [ ! -f /usr/bin/upx ] || [ ! -f /usr/bin/lftp ]; then sudo apt-get update -qq && sudo apt-get install -y -qq --no-install-recommends upx lftp; fi
  # Build biner Go
  - CGO_ENABLED=0 go build -ldflags="-w -s" -o farouter .
  # Kompresi dengan UPX
  - upx --best --lzma farouter

# Langkah eksekusi deployment via LFTP
deploy_script:
  - |
    lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; rm -f /go/farouter; put farouter -o /go/farouter; chmod 700 /go/farouter; put /dev/null -o /go/up"
