# Menentukan Image OS berbasis Ubuntu 24.04
image: Ubuntu2404

# Batasi trigger hanya saat push ke branch main
branches:
  only:
    - main

# Menonaktifkan pembacaan file solusi Visual Studio otomatis
build: off

# Caching folder modul Go dan kompilasi build
cache:
  - /root/go/pkg/mod             # Cache untuk Go modules/dependencies
  - /root/.cache/go-build        # Cache untuk hasil kompilasi Go

# Langkah setup environment dan kompilasi Go
build_script:
  - go version
  - CGO_ENABLED=0 go build -ldflags="-w -s" -o farouter .
  - sudo apt-get update -qq && sudo apt-get install -y -qq --no-install-recommends upx
  - upx --best --lzma farouter

# Langkah instalasi dependency sistem dan eksekusi deployment via LFTP
deploy_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq --no-install-recommends lftp
  - |
    lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; rm -f /go/farouter; put farouter -o /go/farouter; chmod 700 /go/farouter; put /dev/null -o /go/up"
