name: deploy farouter

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go with auto-caching
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true # Meng-cache $GOPATH/pkg/mod dan ~/.cache/go-build secara otomatis

      - name: Build Go binary
        run: CGO_ENABLED=0 go build -ldflags="-w -s" -o farouter .

      - name: Install lftp
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq --no-install-recommends lftp

      - name: Deploy via FTP
        run: |
          lftp -c "open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }}; rm -f /go/farouter; put farouter -o /go/farouter; chmod 700 /go/farouter; put /dev/null -o /go/up"
